#!/bin/sh
# 
# Copyright (c) Sonomos Software S.L. 2012  
# 
# 
# 
# Permission is hereby granted, free of charge, to any person obtaining 
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation 
# the rights to use, copy, modify, merge, publish, distribute, sublicense, 
# and/or sell copies of the Software, and to permit persons to whom the 
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included 
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#  
# This script enables the resigning of XCode archives and outputs a signed IPA file.  
# 
# Run the script from inside the archive folder (look for ~/Library/Developer/XCode/Archives and choose the date) named ".xcarchive".
# 
# 
 
SIGNING_IDENTITY=$1
PROVISIONING_FILE=$2
OUTPUT_APP_NAME=$3
 
if [ $# -lt 3 ]; then
        echo "usage: $0 developer_identity provisioning_file output.ipa" >&2
        exit 1
fi
 
# if it has a file extension, remove it.
APP_NAME=`ls Products/Applications/ | cut -d . -f 1`
 
echo "App name: " $APP_NAME
 
cat << EOF > Entitlements.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>get-task-allow</key>
        <false/>
</dict>
</plist>
EOF
 
cp "Entitlements.plist" "Products/Applications/$APP_NAME.app/Entitlements.plist"
 
NEW_BUNDLE_IDENTIFIER=`egrep -a -A 2 application-identifier $PROVISIONING_FILE | grep string | sed -e 's/<string>//' -e 's/<\/string>//' -e 's/ //' | awk '{split($0,a,"."); print a[2] "." a[3] "." a[4]}'`
 
echo "New bundle ID: " $NEW_BUNDLE_IDENTIFIER
 
# change the top level Plist
/usr/libexec/PlistBuddy -c "Set:ApplicationProperties:CFBundleIdentifier $NEW_BUNDLE_IDENTIFIER" Info.plist
 
# change the bundle ID in the embedded Info.plist 
/usr/libexec/PlistBuddy -c "Set:CFBundleIdentifier $NEW_BUNDLE_IDENTIFIER" "Products/Applications/$APP_NAME.app/Info.plist"
 
/usr/bin/codesign -f -s "$SIGNING_IDENTITY" --resource-rules="Products/Applications/$APP_NAME.app/ResourceRules.plist" --entitlements Entitlements.plist "Products/Applications/$APP_NAME.app"
 
echo "source app name: " "Products/Applications/$APP_NAME.app"
echo "output app name: " $OUTPUT_APP_NAME
echo "signing identity: " "$SIGNING_IDENTITY"
echo "profile name: " "$PROVISIONING_FILE"
/usr/bin/xcrun -sdk iphoneos PackageApplication -v "Products/Applications/$APP_NAME.app" -o $OUTPUT_APP_NAME --sign "$SIGNING_IDENTITY" --embed "$PROVISIONING_FILE"

